export const CHAT_ACTION_TYPES = {
    CHANGE_USER_CHAT: "CHANGE_USER_CHAT",
    FETCH_CURRENT_USER_CHATS_START: "FETCH_CURRENT_USER_CHATS_START",
    FETCH_CURRENT_USER_CHATS_SUCCESS: "FETCH_CURRENT_USER_CHATS_SUCCESS",
    FETCH_CURRENT_USER_CHATS_FAILED: "FETCH_CURRENT_USER_CHATS_FAILED",
    FETCH_USER_MESSAGES_START: "FETCH_USER_MESSAGES_START",
    FETCH_USER_MESSAGES_SUCCESS: "FETCH_USER_MESSAGES_SUCCESS",
    FETCH_USER_MESSAGES_FAILED: "FETCH_USER_MESSAGES_FAILED",
    UPDATE_CHAT_MESSAGES_START: "UPDATE_CHAT_MESSAGES_START",
    UPDATE_CHAT_MESSAGES_SUCCESS: "UPDATE_CHAT_MESSAGES_SUCCESS",
    UPDATE_CHAT_MESSAGES_FAILED: "UPDATE_CHAT_MESSAGES_FAILED"
}