export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    CHECK_USER_SESSION: "CHECK_USER_SESSION",
    GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
    EMAIL_LOG_IN_START: "EMAIL_LOG_IN_START",
    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILED: "SIGN_UP_FAILED ",
    LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
    LOG_IN_FAILED: "LOG_IN_FAILED",
    LOG_OUT_START: "LOG_OUT_START",
    LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
    LOG_OUT_FAILED: "LOG_OUT_FAILED",
    CLEAR_USER_ERRORS: "CLEAR_USER_ERRORS"
}